server:
  port: 8764

spring:
  application:
    name: user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true



info:
  name: ${project.name}
  company: www.jieepre.com
  artifactId: ${project.artifactId}
  version: ${project.version}

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count\sountSql

mybatis:
  type-aliases-package: com.felix.project.model
  mapper-locations: classpath:mapper/*


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS